<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE WorkFlowDefinition SYSTEM "wfdef4.dtd">
<WorkFlowDefinition ApiVersion="4.0"
Origin="JavaAPI"
	Subject="&quot;Test A&quot;"
	Name="TestWorkflowA"
	MainAttachment="&quot;Attachment&quot;"
	AuthorTool="Process Designer"
	versionAgnostic="false"
	validateUsingSchema="true">
	<Field
		Name="OW_GROUPBOX_NAME"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="default"/>
	<Field
		Name="OW_RESUBMIT_DATE"
		ValueExpr="systemtime()"
		Type="time"
		IsArray="false"
		MergeType="default"/>
	<Field
		Name="TEST_EXP_BOOL"
		ValueExpr="true"
		Type="boolean"
		IsArray="false"
		MergeType="default"/>
	<Field
		Name="TEST_EXP_FLOAT"
		ValueExpr="0.0"
		Type="float"
		IsArray="false"
		MergeType="default"/>
	<Field
		Name="TEST_EXP_INT"
		ValueExpr="0"
		Type="int"
		IsArray="false"
		MergeType="default"/>
	<Field
		Name="TEST_EXP_STRING"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="default"/>
	<Field
		Name="TEST_EXP_TIME"
		ValueExpr="systemtime()"
		Type="time"
		IsArray="false"
		MergeType="default"/>
	<Field
		Name="TEST_BOOL"
		ValueExpr="true"
		Type="boolean"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="TEST_STRING"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="TEST_FLOAT"
		ValueExpr="0.0"
		Type="float"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="TEST_INT"
		ValueExpr="0"
		Type="int"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="TEST_TIME"
		ValueExpr="systemtime()"
		Type="time"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="TEST_BOOLS"
		ValueExpr="{true}"
		Type="boolean"
		IsArray="true"
		MergeType="override"/>
	<Field
		Name="TEST_STRINGS"
		ValueExpr="{&quot;&quot;}"
		Type="string"
		IsArray="true"
		MergeType="override"/>
	<Field
		Name="TEST_FLOATS"
		ValueExpr="{0.0}"
		Type="float"
		IsArray="true"
		MergeType="override"/>
	<Field
		Name="TEST_INTS"
		ValueExpr="{0}"
		Type="int"
		IsArray="true"
		MergeType="override"/>
	<Field
		Name="TEST_TIMES"
		ValueExpr="{systemtime()}"
		Type="time"
		IsArray="true"
		MergeType="override"/>
	<Field
		Name="Attachment"
		ValueExpr="&quot;||0|0||&quot;"
		Type="attachment"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="Attachments"
		Description=""
		ValueExpr="{&quot;||0|0||&quot;}"
		Type="attachment"
		IsArray="true"
		MergeType="AppendNoDup"/>
	<Field
		Name="TestGroup"
		Description=""
		ValueExpr="{&quot;user1&quot;,&quot;user2&quot;,&quot;user3&quot;}"
		Type="participant"
		IsArray="true"
		MergeType="AppendNoDup"/>
	<Milestone
		Name="Milestone A"
		Message="&quot;&quot;"
		Level="1"/>
	<Milestone
		Name="Milestone B"
		Message="&quot;&quot;"
		Level="1"/>
	<Map
		Name="Workflow"
		MaxStepId="7" >
		<Step
			StepId="0"
			Name="LaunchStep"
			XCoordinate="49"
			YCoordinate="51"
			RequestedInterface="Approval Launch HTML (FileNet)"
			JoinType="none"
			SplitType="or"
			CanReassign="true"
			CanViewStatus="true"
			CanViewHistory="false"
			IgnoreInvalidUsers="false">
<Parameter
	Name="Attachment"
	ValueExpr="Attachment"
	Type="attachment"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="Attachments"
	Description=""
	ValueExpr="Attachments"
	Type="attachment"
	IsArray="true"
	Mode="inout"/>
<Parameter
	Name="F_Trackers"
	ValueExpr="F_Trackers"
	Type="participant"
	IsArray="true"
	Mode="inout"/>
<Parameter
	Name="OW_GROUPBOX_NAME"
	ValueExpr="OW_GROUPBOX_NAME"
	Type="string"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="OW_RESUBMIT_DATE"
	ValueExpr="OW_RESUBMIT_DATE"
	Type="time"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_BOOL"
	ValueExpr="TEST_BOOL"
	Type="boolean"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_BOOLS"
	ValueExpr="TEST_BOOLS"
	Type="boolean"
	IsArray="true"
	Mode="inout"/>
<Parameter
	Name="TEST_EXP_BOOL"
	ValueExpr="TEST_EXP_BOOL"
	Type="boolean"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_EXP_FLOAT"
	ValueExpr="TEST_EXP_FLOAT"
	Type="float"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_EXP_INT"
	ValueExpr="TEST_EXP_INT"
	Type="int"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_EXP_STRING"
	ValueExpr="TEST_EXP_STRING"
	Type="string"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_EXP_TIME"
	ValueExpr="TEST_EXP_TIME"
	Type="time"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_FLOAT"
	ValueExpr="TEST_FLOAT"
	Type="float"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_FLOATS"
	ValueExpr="TEST_FLOATS"
	Type="float"
	IsArray="true"
	Mode="inout"/>
<Parameter
	Name="TEST_INT"
	ValueExpr="TEST_INT"
	Type="int"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_INTS"
	ValueExpr="TEST_INTS"
	Type="int"
	IsArray="true"
	Mode="inout"/>
<Parameter
	Name="TEST_STRING"
	ValueExpr="TEST_STRING"
	Type="string"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_STRINGS"
	ValueExpr="TEST_STRINGS"
	Type="string"
	IsArray="true"
	Mode="inout"/>
<Parameter
	Name="TEST_TIME"
	ValueExpr="TEST_TIME"
	Type="time"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_TIMES"
	ValueExpr="TEST_TIMES"
	Type="time"
	IsArray="true"
	Mode="inout"/>
<Parameter
	Name="TestGroup"
	Description=""
	ValueExpr="TestGroup"
	Type="participant"
	IsArray="true"
	Mode="inout"/>
			<Route
				SourceStepId="0"
				DestinationStepId="3"/>
<ModelAttributes>
	<ModelAttribute
		Name="UI_StepType"
		Type="int"
		IsArray="false">
			<Value Val="1"/>
	</ModelAttribute>
</ModelAttributes>
		</Step>
		<Step
			StepId="3"
			Name="Step A"
			XCoordinate="210"
			YCoordinate="225"
			RequestedInterface="Approval HTML (FileNet)"
			QueueName="QueueA"
			PostMilestone="Milestone A"
			JoinType="or"
			SplitType="or"
			CanReassign="true"
			CanViewStatus="true"
			CanViewHistory="false"
			IgnoreInvalidUsers="false">
<Parameter
	Name="Attachment"
	ValueExpr="Attachment"
	Type="attachment"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="Attachments"
	Description=""
	ValueExpr="Attachments"
	Type="attachment"
	IsArray="true"
	Mode="inout"/>
<Parameter
	Name="OW_GROUPBOX_NAME"
	ValueExpr="OW_GROUPBOX_NAME"
	Type="string"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="OW_RESUBMIT_DATE"
	ValueExpr="OW_RESUBMIT_DATE"
	Type="time"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_BOOL"
	ValueExpr="TEST_BOOL"
	Type="boolean"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_BOOLS"
	ValueExpr="TEST_BOOLS"
	Type="boolean"
	IsArray="true"
	Mode="inout"/>
<Parameter
	Name="TEST_EXP_BOOL"
	ValueExpr="TEST_EXP_BOOL"
	Type="boolean"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_EXP_FLOAT"
	ValueExpr="TEST_EXP_FLOAT"
	Type="float"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_EXP_INT"
	ValueExpr="TEST_EXP_INT"
	Type="int"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_EXP_STRING"
	ValueExpr="TEST_EXP_STRING"
	Type="string"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_EXP_TIME"
	ValueExpr="TEST_EXP_TIME"
	Type="time"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_FLOAT"
	ValueExpr="TEST_FLOAT"
	Type="float"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_FLOATS"
	ValueExpr="TEST_FLOATS"
	Type="float"
	IsArray="true"
	Mode="inout"/>
<Parameter
	Name="TEST_INT"
	ValueExpr="TEST_INT"
	Type="int"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_INTS"
	ValueExpr="TEST_INTS"
	Type="int"
	IsArray="true"
	Mode="inout"/>
<Parameter
	Name="TEST_STRING"
	ValueExpr="TEST_STRING"
	Type="string"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_STRINGS"
	ValueExpr="TEST_STRINGS"
	Type="string"
	IsArray="true"
	Mode="inout"/>
<Parameter
	Name="TEST_TIME"
	ValueExpr="TEST_TIME"
	Type="time"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_TIMES"
	ValueExpr="TEST_TIMES"
	Type="time"
	IsArray="true"
	Mode="inout"/>
<Parameter
	Name="TestGroup"
	Description=""
	ValueExpr="TestGroup"
	Type="participant"
	IsArray="true"
	Mode="in"/>
			<Route
				SourceStepId="3"
				DestinationStepId="5"/>
<ModelAttributes>
	<ModelAttribute
		Name="UI_StepType"
		Type="int"
		IsArray="false">
			<Value Val="2"/>
	</ModelAttribute>
</ModelAttributes>
		</Step>
		<Step
			StepId="5"
			Name="Step B"
			XCoordinate="360"
			YCoordinate="250"
			RequestedInterface="Approval HTML (FileNet)"
			QueueName="QueueB"
			PostMilestone="Milestone B"
			JoinType="or"
			SplitType="or"
			CanReassign="true"
			CanViewStatus="true"
			CanViewHistory="false"
			IgnoreInvalidUsers="false">
<Parameter
	Name="Attachment"
	ValueExpr="Attachment"
	Type="attachment"
	IsArray="false"
	Mode="in"/>
<Parameter
	Name="Attachments"
	Description=""
	ValueExpr="Attachments"
	Type="attachment"
	IsArray="true"
	Mode="in"/>
<Parameter
	Name="OW_GROUPBOX_NAME"
	ValueExpr="OW_GROUPBOX_NAME"
	Type="string"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="OW_RESUBMIT_DATE"
	ValueExpr="OW_RESUBMIT_DATE"
	Type="time"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_BOOL"
	ValueExpr="TEST_BOOL"
	Type="boolean"
	IsArray="false"
	Mode="in"/>
<Parameter
	Name="TEST_BOOLS"
	ValueExpr="TEST_BOOLS"
	Type="boolean"
	IsArray="true"
	Mode="in"/>
<Parameter
	Name="TEST_EXP_BOOL"
	ValueExpr="TEST_EXP_BOOL"
	Type="boolean"
	IsArray="false"
	Mode="in"/>
<Parameter
	Name="TEST_EXP_FLOAT"
	ValueExpr="TEST_EXP_FLOAT"
	Type="float"
	IsArray="false"
	Mode="in"/>
<Parameter
	Name="TEST_EXP_INT"
	ValueExpr="TEST_EXP_INT"
	Type="int"
	IsArray="false"
	Mode="in"/>
<Parameter
	Name="TEST_EXP_STRING"
	ValueExpr="TEST_EXP_STRING"
	Type="string"
	IsArray="false"
	Mode="in"/>
<Parameter
	Name="TEST_EXP_TIME"
	ValueExpr="TEST_EXP_TIME"
	Type="time"
	IsArray="false"
	Mode="in"/>
<Parameter
	Name="TEST_FLOAT"
	ValueExpr="TEST_FLOAT"
	Type="float"
	IsArray="false"
	Mode="in"/>
<Parameter
	Name="TEST_FLOATS"
	ValueExpr="TEST_FLOATS"
	Type="float"
	IsArray="true"
	Mode="in"/>
<Parameter
	Name="TEST_INT"
	ValueExpr="TEST_INT"
	Type="int"
	IsArray="false"
	Mode="in"/>
<Parameter
	Name="TEST_INTS"
	ValueExpr="TEST_INTS"
	Type="int"
	IsArray="true"
	Mode="in"/>
<Parameter
	Name="TEST_STRING"
	ValueExpr="TEST_STRING"
	Type="string"
	IsArray="false"
	Mode="in"/>
<Parameter
	Name="TEST_STRINGS"
	ValueExpr="TEST_STRINGS"
	Type="string"
	IsArray="true"
	Mode="in"/>
<Parameter
	Name="TEST_TIME"
	ValueExpr="TEST_TIME"
	Type="time"
	IsArray="false"
	Mode="in"/>
<Parameter
	Name="TEST_TIMES"
	ValueExpr="TEST_TIMES"
	Type="time"
	IsArray="true"
	Mode="in"/>
<Parameter
	Name="TestGroup"
	Description=""
	ValueExpr="TestGroup"
	Type="participant"
	IsArray="true"
	Mode="inout"/>
			<Route
				SourceStepId="5"
				DestinationStepId="7"/>
<ModelAttributes>
	<ModelAttribute
		Name="UI_StepType"
		Type="int"
		IsArray="false">
			<Value Val="2"/>
	</ModelAttribute>
</ModelAttributes>
		</Step>
		<Step
			StepId="7"
			Name="Step TestGroup"
			XCoordinate="390"
			YCoordinate="375"
			RequestedInterface="Approval HTML (FileNet)"
			QueueName="Inbox"
			JoinType="or"
			SplitType="or"
			CanReassign="true"
			CanViewStatus="true"
			CanViewHistory="false"
			IgnoreInvalidUsers="false">
			<Participant Val="TestGroup" />
<Parameter
	Name="Attachment"
	ValueExpr="Attachment"
	Type="attachment"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="Attachments"
	Description=""
	ValueExpr="Attachments"
	Type="attachment"
	IsArray="true"
	Mode="inout"/>
<Parameter
	Name="OW_GROUPBOX_NAME"
	ValueExpr="OW_GROUPBOX_NAME"
	Type="string"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="OW_RESUBMIT_DATE"
	ValueExpr="OW_RESUBMIT_DATE"
	Type="time"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_BOOL"
	ValueExpr="TEST_BOOL"
	Type="boolean"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_BOOLS"
	ValueExpr="TEST_BOOLS"
	Type="boolean"
	IsArray="true"
	Mode="inout"/>
<Parameter
	Name="TEST_EXP_BOOL"
	ValueExpr="TEST_EXP_BOOL"
	Type="boolean"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_EXP_FLOAT"
	ValueExpr="TEST_EXP_FLOAT"
	Type="float"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_EXP_INT"
	ValueExpr="TEST_EXP_INT"
	Type="int"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_EXP_STRING"
	ValueExpr="TEST_EXP_STRING"
	Type="string"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_EXP_TIME"
	ValueExpr="TEST_EXP_TIME"
	Type="time"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_FLOAT"
	ValueExpr="TEST_FLOAT"
	Type="float"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_FLOATS"
	ValueExpr="TEST_FLOATS"
	Type="float"
	IsArray="true"
	Mode="inout"/>
<Parameter
	Name="TEST_INT"
	ValueExpr="TEST_INT"
	Type="int"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_INTS"
	ValueExpr="TEST_INTS"
	Type="int"
	IsArray="true"
	Mode="inout"/>
<Parameter
	Name="TEST_STRING"
	ValueExpr="TEST_STRING"
	Type="string"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_STRINGS"
	ValueExpr="TEST_STRINGS"
	Type="string"
	IsArray="true"
	Mode="inout"/>
<Parameter
	Name="TEST_TIME"
	ValueExpr="TEST_TIME"
	Type="time"
	IsArray="false"
	Mode="inout"/>
<Parameter
	Name="TEST_TIMES"
	ValueExpr="TEST_TIMES"
	Type="time"
	IsArray="true"
	Mode="inout"/>
<Parameter
	Name="TestGroup"
	Description=""
	ValueExpr="TestGroup"
	Type="participant"
	IsArray="true"
	Mode="inout"/>
<ModelAttributes>
	<ModelAttribute
		Name="UI_StepType"
		Type="int"
		IsArray="false">
			<Value Val="2"/>
	</ModelAttribute>
</ModelAttributes>
		</Step>
	</Map>
</WorkFlowDefinition>
