DROP TABLE IF EXISTS ow_role;
CREATE TABLE  ow_role (
  ROLE_ID INT NOT NULL IDENTITY,
  ROLE_NAME varchar(255) NOT NULL,
  ROLE_RESOURCE varchar(255) NOT NULL,
  ROLE_ACCESS INT DEFAULT '-1',
  ROLE_ACCESS_MASK INT DEFAULT '-1',
  CATEGORY INT NOT NULL
);