--
-- PostgreSQL database
-- Insert Contract Management Solution Template - Region and country for OwDependentComboboxFieldControl sample
--
SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = off;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET escape_string_warning = off;

INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'AFGHANISTAN (AF)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'ÅLAND ISLANDS (AX)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'ALBANIA (AL)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'ALGERIA (DZ)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'AMERICAN SAMOA (AS)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'ANDORRA (AD)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'ANGOLA (AO)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'ANGUILLA (AI)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'ARGENTINA (AR)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'ANTIGUA AND BARBUDA (AG)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'ARUBA (AW)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'ARMENIA (AM)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'AUSTRALIA (AU)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'AUSTRIA (AT)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'AZERBAIJAN (AZ)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'BAHAMAS (BS)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'BAHRAIN (BH)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'BANGLADESH (BD)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'BARBADOS (BB)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'BELARUS (BY)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'BELGIUM (BE)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'BELIZE (BZ)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'BENIN (BJ)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'BERMUDA (BM)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'BHUTAN (BT)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'BOLIVIA, PLURINATIONAL STATE OF (BO)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'BONAIRE, SINT EUSTATIUS AND SABA (BQ)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'BOSNIA AND HERZEGOVINA (BA)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'BOTSWANA (BW)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'BOUVET ISLAND (BV)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'BRAZIL (BR)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'BRITISH INDIAN OCEAN TERRITORY (IO)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'BRUNEI DARUSSALAM (BN)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'BULGARIA (BG)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'BURKINA FASO (BF)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'BURUNDI (BI)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'CAMBODIA (KH)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'CAMEROON (CM)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'CANADA (CA)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'CAPE VERDE (CV)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'CAYMAN ISLANDS (KY)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'CENTRAL AFRICAN REPUBLIC (CF)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'CHAD (TD)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'CHILE (CL)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'CHINA (CN)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'CHRISTMAS ISLAND (CX)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'COCOS (KEELING) ISLANDS (CC)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'COLOMBIA (CO)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'COMOROS (KM)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'CONGO (CG)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE (CD)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'COOK ISLANDS (CK)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'COSTA RICA (CR)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'CÔTE D\'IVOIRE (CI)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'CROATIA (HR)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'CUBA (CU)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'CURAÇAO (CW)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'CYPRUS (CY)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'CZECH REPUBLIC (CZ)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'DENMARK (DK)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'DJIBOUTI (DJ)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'DOMINICA (DM)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'DOMINICAN REPUBLIC (DO)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'ECUADOR (EC)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'EGYPT (EG)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'EL SALVADOR (SV)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'EQUATORIAL GUINEA (GQ)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'ERITREA (ER)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'ESTONIA (EE)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'ETHIOPIA (ET)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'FALKLAND ISLANDS (MALVINAS) (FK)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'FAROE ISLANDS (FO)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'FIJI (FJ)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'FINLAND (FI)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'FRANCE (FR)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'FRENCH GUIANA (GF)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'FRENCH POLYNESIA (PF)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'FRENCH SOUTHERN TERRITORIES (TF)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'GABON (GA)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'GAMBIA (GM)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'GEORGIA (GE)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'GERMANY (DE)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'GHANA (GH)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'GIBRALTAR (GI)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'GREECE (GR)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'GREENLAND (GL)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'GRENADA (GD)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'GUADELOUPE (GP)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'GUAM (GU)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'GUATEMALA (GT)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'GUERNSEY (GG)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'GUINEA (GN)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'GUINEA-BISSAU (GW)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'GUYANA (GY)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'HAITI (HT)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'HEARD ISLAND AND MCDONALD ISLANDS (HM)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'HOLY SEE (VATICAN CITY STATE) (VA)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'HONDURAS (HN)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'HONG KONG (HK)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'HUNGARY (HU)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'ICELAND (IS)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'INDIA (IN)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'INDONESIA (ID)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'IRAN, ISLAMIC REPUBLIC OF (IR)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'IRAQ (IQ)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'IRELAND (IE)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'ISLE OF MAN (IM)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'ISRAEL (IL)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'ITALY (IT)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'JAMAICA (JM)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'JAPAN (JP)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'JERSEY (JE)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'JORDAN (JO)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'KAZAKHSTAN (KZ)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'KENYA (KE)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'KIRIBATI (KI)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF (KP)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'KOREA, REPUBLIC OF (KR)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'KUWAIT (KW)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'KYRGYZSTAN (KG)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC (LA)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'LATVIA (LV)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'LEBANON (LB)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'LESOTHO (LS)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'LIBERIA (LR)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'LIBYA (LY)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'LIECHTENSTEIN (LI)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'LITHUANIA (LT)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'LUXEMBOURG (LU)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'MACAO (MO)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF (MK)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'MADAGASCAR (MG)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'MALAWI (MW)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'MALAYSIA (MY)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'MALDIVES (MV)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'MALI (ML)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'MALTA (MT)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'MARSHALL ISLANDS (MH)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'MARTINIQUE (MQ)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'MAURITANIA (MR)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'MAURITIUS (MU)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'MAYOTTE (YT)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'MEXICO (MX)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'MICRONESIA, FEDERATED STATES OF (FM)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'MOLDOVA, REPUBLIC OF (MD)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'MONACO (MC)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'MONGOLIA (MN)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'MONTENEGRO (ME)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'MONTSERRAT (MS)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'MOROCCO (MA)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'MOZAMBIQUE (MZ)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'MYANMAR (MM)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'NAMIBIA (NA)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'NAURU (NR)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'NEPAL (NP)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'NETHERLANDS (NL)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'NEW CALEDONIA (NC)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'NEW ZEALAND (NZ)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'NICARAGUA (NI)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'NIGER (NE)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'NIGERIA (NG)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'NIUE (NU)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'NORFOLK ISLAND (NF)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'NORTHERN MARIANA ISLANDS (MP)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'NORWAY (NO)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'OMAN (OM)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'PAKISTAN (PK)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'PALAU (PW)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'PALESTINE, STATE OF (PS)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'PANAMA (PA)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'PAPUA NEW GUINEA (PG)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'PARAGUAY (PY)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'PERU (PE)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'PHILIPPINES (PH)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'PITCAIRN (PN)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'POLAND (PL)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'PORTUGAL (PT)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'PUERTO RICO (PR)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'QATAR (QA)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'RÉUNION (RE)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'ROMANIA (RO)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'RUSSIAN FEDERATION (RU)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'RWANDA (RW)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'SAINT BARTHÉLEMY (BL)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA (SH)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'SAINT KITTS AND NEVIS (KN)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'SAINT LUCIA (LC)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'SAINT MARTIN (FRENCH PART) (MF)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'SAINT PIERRE AND MIQUELON (PM)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'SAINT VINCENT AND THE GRENADINES (VC)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'SAMOA (WS)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'SAN MARINO (SM)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'SAO TOME AND PRINCIPE (ST)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'SAUDI ARABIA (SA)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'SENEGAL (SN)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'SERBIA (RS)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'SEYCHELLES (SC)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'SIERRA LEONE (SL)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'SINGAPORE (SG)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'SINT MAARTEN (DUTCH PART) (SX)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'SLOVAKIA (SK)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'SLOVENIA (SI)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'SOLOMON ISLANDS (SB)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'SOMALIA (SO)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'SOUTH AFRICA (ZA)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS (GS)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'SOUTH SUDAN (SS)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'SPAIN (ES)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'SRI LANKA (LK)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'SUDAN (SD)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'SURINAME (SR)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'SVALBARD AND JAN MAYEN (SJ)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'SWAZILAND (SZ)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'SWEDEN (SE)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'SWITZERLAND (CH)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'SYRIAN ARAB REPUBLIC (SY)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'TAIWAN, PROVINCE OF CHINA (TW)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'TAJIKISTAN (TJ)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'TANZANIA, UNITED REPUBLIC OF (TZ)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'THAILAND (TH)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'TIMOR-LESTE (TL)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'TOGO (TG)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'TOKELAU (TK)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'TONGA (TO)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'TRINIDAD AND TOBAGO (TT)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'TUNISIA (TN)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'TURKEY (TR)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'TURKMENISTAN (TM)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'TURKS AND CAICOS ISLANDS (TC)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'TUVALU (TV)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'UGANDA (UG)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'UKRAINE (UA)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'UNITED ARAB EMIRATES (AE)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'UNITED KINGDOM (GB)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'UNITED STATES (US)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'UNITED STATES MINOR OUTLYING ISLANDS (UM)');
INSERT INTO ow_dblookup (region, country) VALUES ('AMER', 'URUGUAY (UY)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'UZBEKISTAN (UZ)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'VANUATU (VU)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'VIET NAM (VN)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'VIRGIN ISLANDS, BRITISH (VG)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'VIRGIN ISLANDS, U.S. (VI)');
INSERT INTO ow_dblookup (region, country) VALUES ('APAC', 'WALLIS AND FUTUNA (WF)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'WESTERN SAHARA (EH)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'YEMEN (YE)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'ZAMBIA (ZM)');
INSERT INTO ow_dblookup (region, country) VALUES ('EMEA', 'ZIMBABWE (ZW)');
