DROP TABLE IF EXISTS `owd`.`MW_ROLE`;
CREATE TABLE  `owd`.`MW_ROLE` (
  `ROLE_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ROLE_NAME` varchar(255) NOT NULL,
  `ROLE_RESOURCE` varchar(255) NOT NULL,
  `ROLE_ACCESS` int(11) NOT NULL DEFAULT '-1',
  `ROLE_ACCESS_MASK` int(11) NOT NULL DEFAULT '-1',
  `CATEGORY` int(10) unsigned NOT NULL,
  PRIMARY KEY (`ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;