
DROP DATABASE  IF EXISTS  owd;

DROP ROLE  IF EXISTS owdemo;

CREATE ROLE owdemo LOGIN ENCRYPTED PASSWORD 'owdemo'
  SUPERUSER CREATEDB CREATEROLE
   VALID UNTIL 'infinity';

CREATE DATABASE owd
  WITH OWNER = "owdemo"
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       CONNECTION LIMIT = -1;
       
